# isso poupa de criar um um container pelo terminal, mas seria assim pelo terminal:

# docker run --name trybe-mysql -p 3306:3306 --platform linux/x86_64 -e MYSQL_ROOT_PASSWORD=password -d mysql:5.7

# docker exec -i 3ae mysql -h127.0.0.1 -uroot -ppassword < sakila.sql

version: '3'

services:
  db:
    image: mysql:5.7
    # platform: linux/x86_64
    ports:
    - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root